preload = ~/.config/hypr/wallpapers/bird.jpeg
preload = ~/.config/hypr/wallpapers/cave.png
preload = ~/.config/hypr/wallpapers/beast.jpeg
preload = ~/.config/hypr/wallpapers/ciri.png
preload = ~/.config/hypr/wallpapers/crows.jpeg
preload = ~/.config/hypr/wallpapers/dogs.jpeg
preload = ~/.config/hypr/wallpapers/fire.jpeg
preload = ~/.config/hypr/wallpapers/forest.jpeg
preload = ~/.config/hypr/wallpapers/hunt.jpeg
preload = ~/.config/hypr/wallpapers/khaer.png
preload = ~/.config/hypr/wallpapers/meditate.jpeg
preload = ~/.config/hypr/wallpapers/mist.jpeg
preload = ~/.config/hypr/wallpapers/noonwraith.jpeg
preload = ~/.config/hypr/wallpapers/schools.jpeg
preload = ~/.config/hypr/wallpapers/town.jpeg
preload = ~/.config/hypr/wallpapers/werewolf.jpeg
preload = ~/.config/hypr/wallpapers/yen.jpeg

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = eDP-1,~/.config/hypr/wallpapers/crows.jpeg
#if more than one monitor in use, can load a 2nd image

#enable splash text rendering over the wallpaper
#splash = true

#fully disable ipc
# ipc = off

